version: "3.8"

services:
  calbot:
    build: .
    image: calbot:v0
    container_name: calbot_container
    volumes:
      - "./:/app"
    env_file:
      - .env
    command:
      - sh
      - -c
      - "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && python /app/calbot.py /app/calbot.cfg"